language: generic
dist: trusty
sudo: false

os:
  - linux
  - osx

env:
  matrix:
    - PYTHON_VERSION=2.7
    - PYTHON_VERSION=3.4
    - PYTHON_VERSION=3.5
    - PYTHON_VERSION=3.6
  global:
    - MINCONDA_VERSION="latest"
    - MINCONDA_LINUX="Linux-x86_64"
    - MINCONDA_OSX="MacOSX-x86_64"

before_install:
  - if [[ "$PYTHON_VERSION" == "2.7" ]]; then
      MINCONDA_PYTHON_VERSION=2;
    else
      MINCONDA_PYTHON_VERSION=3;
    fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then
      MINCONDA_OS=$MINCONDA_LINUX;
    elif [[ "$TRAVIS_OS_NAME" == "osx" ]]; then
      MINCONDA_OS=$MINCONDA_OSX;
    fi
  - wget "http://repo.continuum.io/miniconda/Miniconda$MINCONDA_PYTHON_VERSION-$MINCONDA_VERSION-$MINCONDA_OS.sh" -O miniconda.sh;
  - bash miniconda.sh -b -p $HOME/miniconda
  - export PATH="$HOME/miniconda/bin:$PATH"
  - conda config --set always_yes yes
  - conda update -q conda
  - conda create -q -n test-environment python=$PYTHON_VERSION pip numpy pytest
  - source activate test-environment
  - "pip install 'coverage<4'"  # After 4, there is some issue when using python 3.2
  - "pip install -r requirements.txt"
  - "conda list" # Show the package versions (for debugging)

install:
  - "pip install ."
  - "echo done"

# command to run tests, e.g. python setup.py test
script:
  - if [[ "$PYTHON_VERSION" == "3.6" ]]; then
      coverage run --source=mcfly -m pytest;
    else
      py.test  ;
    fi
  

after_script:
  - "pip install scrutinizer-ocular"
  - "ocular"

