build: false

platform:
  - x86
  - x64

environment:
  matrix:
    # Python 2.7
    - MINICONDA: C:\Miniconda-x64
    # Python 3.5, 32 bit
    - MINICONDA: C:\Miniconda35-x64
    # Python 3.6
    - MINICONDA: C:\Miniconda36-x64

matrix:
  exclude:
    # Python 2.7
    - MINICONDA: C:\Miniconda
      platform: x64
    # Python 3.5
    - MINICONDA: C:\Miniconda35
      platform: x64
    # Python 3.6
    - MINICONDA: C:\Miniconda36
      platform: x64
  allow_failures:
    - MINICONDA: C:\Miniconda-x64
    - MINICONDA: C:\Miniconda36-x64

init:
  - "set PATH=%MINICONDA%;%MINICONDA%\\Scripts;%MINICONDA%\\Library\\bin;%PATH%"

install:
  - conda config --set always_yes yes --set changeps1 no
  - conda config --add channels conda-forge
  - conda update -q conda
  - conda install pip numpy scipy
  - "pip install -q pytest"
  
  # Added --ignore-installed in next line because of failures like in
  # https://ci.appveyor.com/project/NLeSC/mcfly/builds/26750694/job/1klik02e6464okfc
  # for which the used fix is suggested here: https://github.com/ContinuumIO/anaconda-issues/issues/542.
  - "pip install -qr requirements.txt --ignore-installed"
  - "pip install .  --ignore-installed"
  - "echo done"

# command to run tests, e.g. python setup.py test
test_script:
  - pytest
