name: mcfly27
channels: !!python/tuple
- !!python/unicode
  'defaults'
dependencies:
- cairo=1.14.8=0
- cycler=0.10.0=py27_0
- dbus=1.10.10=0
- expat=2.1.0=0
- fontconfig=2.12.1=3
- freetype=2.5.5=2
- funcsigs=1.0.2=py27_0
- functools32=3.2.3.2=py27_0
- glib=2.50.2=1
- gst-plugins-base=1.8.0=0
- gstreamer=1.8.0=0
- h5py=2.6.0=np111py27_2
- hdf5=1.8.17=1
- icu=54.1=0
- jbig=2.1=0
- jpeg=9b=0
- keras=1.1.1=py27_0
- libffi=3.2.1=1
- libgcc=5.2.0=0
- libgfortran=3.0.0=1
- libiconv=1.14=0
- libpng=1.6.27=0
- libprotobuf=3.0.0=0
- libtiff=4.0.6=3
- libxcb=1.12=1
- libxml2=2.9.4=0
- matplotlib=2.0.0=np111py27_0
- mkl=2017.0.1=0
- mkl-service=1.1.2=py27_3
- mock=2.0.0=py27_0
- numpy=1.11.3=py27_0
- olefile=0.44=py27_0
- openssl=1.0.2k=0
- pandas=0.19.2=np111py27_1
- pbr=1.10.0=py27_0
- pcre=8.39=1
- pillow=4.0.0=py27_1
- pip=9.0.1=py27_1
- pixman=0.34.0=0
- protobuf=3.0.0=py27_1
- pycairo=1.10.0=py27_0
- pyparsing=2.1.4=py27_0
- pyqt=5.6.0=py27_2
- python=2.7.13=0
- python-dateutil=2.6.0=py27_0
- pytz=2016.10=py27_0
- pyyaml=3.12=py27_0
- qt=5.6.2=3
- readline=6.2=2
- scikit-learn=0.18.1=np111py27_1
- scipy=0.18.1=np111py27_1
- setuptools=27.2.0=py27_0
- sip=4.18=py27_0
- six=1.10.0=py27_0
- sqlite=3.13.0=0
- subprocess32=3.2.7=py27_0
- tensorflow=0.10.0rc0=np111py27_0
- theano=0.8.2=py27_0
- tk=8.5.18=0
- wheel=0.29.0=py27_0
- xz=5.2.2=1
- yaml=0.1.6=0
- zlib=1.2.8=3

